### ISSUE TITLE
Solve this equation using Newton Raphson method

### ISSUE THREAD

**Issue by keshav2002** [keshav2002/python-scripts#1]
(i) Water vapour splits into Oxygen and Hydrogen at
higher temperature as 

> 2H<sub>2</sub>O -> 2H<sub>2</sub> + O<sub>2</sub>

The model for the _reaction rate_ `r` and _mole fraction_ `f` of
H<sub>2</sub>O is given by

> r = R<sub>2</sub>/R<sub>1</sub> 

,with concentrations R<sub>1</sub> = \[H<sub>2</sub>O\]<sup>2</sup>
, R<sub>2</sub> = \[H<sub>2</sub>\]<sup>2</sup>\[O<sub>2</sub>\] and

> k = f/(1-f) \sqrt{2p/(2+f)}

where k = 0.04 is a given reaction equilibrium constant
and p = 3.5atm is the total pressure at some temperature T.

> F = F(f) = 0.04 - f/(1-f) \sqrt{7/(2+f)} = 0

The Newton’s method for F is
> f<sub>i+1</sub> = f<sub>i</sub> - F(f<sub>i</sub>)/F’(f<sub>i</sub>) , i=0,1,2…

Solve this equation using the Newton Raphson method.

**Comment by shrinidhi99** [comment]
@keshav2002 can I take this up?
